### ISSUE TITLE
Can you provide your count and metadata data to run your code ?

### ISSUE THREAD

**Issue by pangkun97** [MasahiroNakano-hub/ImmuNexUT_SLE#1]
Glad to see your high-level research. I noticed that the count and metadata data used in the code part you provided could not be found. Can you provide me with your count and metadata data? I would be grateful. My email address is pangkun_bio@foxmail.com.

**Comment by MasahiroNakano-hub** [comment]
Thanks for contacting me.

RNA-seq data used in this study and metadata including case/control, age and sex information are available at the National Bioscience Database Center (NBDC) Human Database.
